### ISSUE TITLE
Allow cmd to be customized in settings

### ISSUE THREAD

**Issue by BrandonSurowiec** [gerardroche/sublime-phpunit#34]
I have phpunit installed globally, and I would always like the `phpunit` cmd to be used when running the tests even if my `vendor/bin/phpunit` exists. Can that be added as a setting?

**Comment by gerardroche** [comment]
How about an setting: `phpunit.cmd`?

Currently we figure out the command to use by checking if `vendor/bin/phpunit` exists relative to the `phpunit.xml` configuration file, if not, then we fallback to what would be the global command `phpunit`.

So, if `phpunit.cmd` is set that will be used otherwise the default is to check for a composer installed phpunit, or default to the global one.

You will then be able to configure it globally or project specific:

`Project > Edit Project`

```
{
    "settings": {
        "phpunit.save_all_on_run": false
    }
}
```

**Comment by gerardroche** [comment]
Or maybe easier, add the option `phpunit.composer_support` which defaults to true?

**Comment by gerardroche** [comment]
I went with the setting `phpunit.composer`.

```
    // Enable/disable composer installed PHPUnit support.
    //
    // For example, if composer installed PHPUnit exists then it is used as the
    // command to run PHPUnit, otherwise defaults to the command "phpunit".
    "phpunit.composer": true,
```

**Comment by BrandonSurowiec** [comment]
Fast! Awesome, ty :)
