### ISSUE TITLE
Force PHPUnit to run via Composer

### ISSUE THREAD

**Issue by SaeedPrez** [gerardroche/sublime-phpunit#48]
Hello,

Thanks for an awesome plugin.

Is it possible to add setting to force PHPUnit to run via composer?

**Comment by gerardroche** [comment]
How do you mean force? 

Currently composer support is enabled by default. If a Composer installed PHPUnit is found it is used, otherwise a fallback is used. The fallback is to just run the command `phpunit` which assumes PHPUnit is on your system path, if it's not on your system path then it fails normally.

By force, do you mean not to use any fallback and just fail straight away if no Composer installed PHPUnit is found?

**Comment by SaeedPrez** [comment]
Thanks for your reply.

I was having problems getting it work on my Windows 10 system as I had PHPUnit installed globally with composer. So I was setting composer to `true` but it was trying to run `vendor/bin/phpunit` and I wanted to force the global composer. But playing around with it a little I finally figured out that composer setting = local composer package so it's working like a charm now ☺
