### ISSUE TITLE
How to disable this line error display in editor

### ISSUE THREAD

**Issue by LespiletteMaxime** [gerardroche/sublime-phpunit#67]
When I run the test it display line error in editor, is it possible to disable this feature ? 

![](https://s12.postimg.org/m4m3xazf1/Capture_du_2017-07-10_11-36-41.png)

Thanks

**Comment by gerardroche** [comment]
Those are build errors that baked into Sublime. There are recent new feature


re: https://stackoverflow.com/questions/39714095/dark-red-messages-in-sublime

They can be disabled.

### User

`Menu > Preferences > Settings` (`Preferences.sublime-settings - User`)

```
{
    "show_errors_inline": false
}
```

### Per-Project

`Menu > Project > Edit Project`

```
{
    "settings": {
        "show_errors_inline": false
    }
}
```

**Comment by myself379** [comment]
Thanks for this info. I'm newbie to TDD and looking forward improving the workflow so the TDD doesn't get into the way when I'm learning. This should be sticky.

p/s: I'm using Windows 10 and I'm looking is it possible to trigger the feedback console to new window instead of the bottom, kinda hard to scroll up to view the actual errors.
