### ISSUE TITLE
User Keymaps stopped working

### ISSUE THREAD

**Issue by godbout** [gerardroche/sublime-phpunit#71]
I had personal key maps, they all stopped working. I thought it was an issue with Sublime Text but all the other packages and personal key maps work. It seems the "context" arguments are causing issues.

**Comment by gerardroche** [comment]
The default keybindings were removed in v2.3.0. 

Your custom keybindings must be using the setting `phpunit.keymaps` which has also been removed so your custom keybindings are disabled because `phpunit.keymaps` now evaluates to false.

You can set your preferred keybindings explained below. Also consider using PHPUnitKit along with the new [Test](https://github.com/gerardroche/sublime-test) package which attempts to unify test plugins into one set of commands and keymaps (as of writing it's not yet [available on Package Control](https://github.com/wbond/package_control_channel/pull/6534). 

## [2.3.0](CHANGELOG.md) - 2017-08-23

### Added

* Added: Improved color scheme support for test results
* Added: `:TestSwitch` now positions cursor at the row of the class definition

### Removed

* The default key bindings have been removed, instead add your preferred key bindings:

  `Menu > Preferences > Key Bindings`

  ```json
  [
      { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite" },
      { "keys": ["ctrl+shift+f"], "command": "phpunit_test_file" },
      { "keys": ["ctrl+shift+n"], "command": "phpunit_test_nearest" },
      { "keys": ["ctrl+shift+l"], "command": "phpunit_test_last" },
      { "keys": ["ctrl+shift+v"], "command": "phpunit_test_visit" },
      { "keys": ["ctrl+shift+s"], "command": "phpunit_test_switch" },
      { "keys": ["ctrl+shift+c"], "command": "phpunit_test_cancel" },
      { "keys": ["ctrl+shift+r"], "command": "phpunit_test_results" },
  ]
  ```

  The following key bindings remain the same:

  Key | Description
  --- | -----------
  `F4` | Jump to Next Failure
  `Shift+F4` | Jump to Previous Failure

**Comment by godbout** [comment]
Oops. Missed that update. Thanks @gerardroche.
